version: "3.5"

services:
    php-fpm:
        build: './docker/php-fpm/'
        volumes:
            - './:/var/www/html/'

    nginx:
        image: nginx:1.17
        volumes:
            - './:/var/www/html/'
            - './docker/nginx/host.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - "3333:80"

    mysql:
        image: mysql:5.7
        volumes:
            - './docker/mysql/data:/var/lib/mysql'
            - './docker/mysql/init.sh:/docker-entrypoint-initdb.d/init.sh'
        environment:
            MYSQL_ROOT_PASSWORD: $DB_PASSWORD
            MAIN_DATABASE_NAME: $DB_NAME

    redis:
        image: redis