version: "3.5"

services:
    php:
        build: './docker/php-fpm/'
        volumes:
            - './:/var/www/html/'
        networks:
            backend:

    nginx:
        image: nginx:1.17
        volumes:
            - './:/var/www/html/'
            - './docker/nginx/host.conf:/etc/nginx/conf.d/default.conf:ro'
        networks:
            frontend:
                ipv4_address: $DOCKER_NGINX_IP
            backend:
        links:
            - "php:php-fpm"

    mysql:
        image: mysql:5.7
        volumes:
            - './docker/mysql/data:/var/lib/mysql'
            - './docker/mysql/init.sh:/docker-entrypoint-initdb.d/init.sh'
        environment:
            MYSQL_ROOT_PASSWORD: $DB_PASSWORD
            MAIN_DATABASE_NAME: $DB_NAME
        networks:
            - backend

    redis:
        image: redis
        networks:
            - backend

networks:
    frontend:
        ipam:
            config:
                - subnet: $DOCKER_SUBNET
    backend:
